"""add theme and language to users

Revision ID: 0a80fa0e3cb6
Revises: 99af59bb7d1d
Create Date: 2025-06-17 19:32:57.398893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a80fa0e3cb6'
down_revision: Union[str, None] = '99af59bb7d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
