"""add real_name and nick_name to users

Revision ID: 99af59bb7d1d
Revises: 
Create Date: 2025-06-17 18:52:44.870113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99af59bb7d1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nick_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nick_name')
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
